### ISSUE TITLE
Basic example not working 

### ISSUE THREAD

**Issue by justin-hackin** [keithwhor/FSO.js#1]
Created a basic page with you example in it and it doesn't seem to work when run on localhost server.

``` html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <script type="text/javascript" src="fso.min.js"></script>

</head>
<body>
  <script> 
    var fso = new FSO(1024 * 1024 * 1024, true); // Create 1GB of temp storage

    var fsq = fso.createQueue();

    // Queues process commands sequentially,
    // prepare your queue like so:
    fsq.mkdir('hello');
    fsq.write('hello/world.txt', 'Hello World');
    fsq.read('hello/world.txt', function(data) { console.log(data); });

    // Finally, execute asynchronously.
    fsq.execute();
  </script>
</body>
</html>
```

I'm running Chrome Version 37.0.2062.120 (64-bit)

**Comment by keithwhor** [comment]
http://www.w3.org/TR/file-system-api/

The W3C specification for the file system API was discontinued a few months after this library was published.

Chrome should still have partial support so I can look into the issue in the next couple of days, but I'd recommend using IndexedDB (https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) to store large chunks of offline data.

**Comment by DieterVanRossem** [comment]
It might be worth putting this at the top of your project. I started testing, reading your docs, googl'ing...
Too bad it does not work anymore.

**Comment by keithwhor** [comment]
Going to do so now. Sorry for any inconvenience!
